version: 2.1

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: skpr/node:14-1.x
    working_directory: /data
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ arch }}-{{ checksum "package-lock.json" }}
            - deps-{{ arch }}-
      - run:
          name: Init
          command: npm ci
      - save_cache:
          key: deps-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
